from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter
import json


def generate_pdf_from_json(json_path, pdf_path):
    with open(json_path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    data = raw["data"]
    meta = raw.get("meta", {})

    doc = SimpleDocTemplate(pdf_path, pagesize=letter)
    styles = getSampleStyleSheet()

    # ---------------------------
    # Styles (aligned with UI)
    # ---------------------------
    title_style = ParagraphStyle(
        name="Title",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=12
    )

    section_title = ParagraphStyle(
        name="SectionTitle",
        parent=styles["Heading2"],
        fontSize=14,
        spaceAfter=8
    )

    normal = styles["Normal"]

    small_gray = ParagraphStyle(
        name="SmallGray",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.grey
    )

    table_header = ParagraphStyle(
        name="TableHeader",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.black,
        spaceAfter=4,
        fontName="Helvetica-Bold"
    )

    story = []

    # ---------------------------
    # 🔹 Title
    # ---------------------------
    story.append(Paragraph("Risk Summary Report", title_style))
    story.append(Spacer(1, 10))

    # ---------------------------
    # 🔹 Summary (remarks)
    # ---------------------------
    story.append(Paragraph("Summary", section_title))
    story.append(Paragraph(data.get("remarks", ""), normal))
    story.append(Spacer(1, 12))

    # ---------------------------
    # 🔹 Risk Overview (2-column)
    # ---------------------------
    overview_table = Table([
        [
            Paragraph(f"<b>Overall Risk</b><br/>{data.get('overall_risk', '')}", normal),
            Paragraph(f"<b>Risk Score</b><br/>{data.get('risk_score', '')}", normal),
        ]
    ], colWidths=["50%", "50%"])

    overview_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("PADDING", (0, 0), (-1, -1), 10),
    ]))

    story.append(overview_table)
    story.append(Spacer(1, 16))

    # ---------------------------
    # 🔹 Sections Table (MAIN PART)
    # ---------------------------
    story.append(Paragraph("Detailed Assessment", section_title))

    table_data = []

    # Header
    table_data.append([
        Paragraph("S No.", table_header),
        Paragraph("Section", table_header),
        Paragraph("Subject", table_header),
        Paragraph("Summary", table_header),
    ])

    # Rows
    for idx, sec in enumerate(data.get("sections", [])):
        table_data.append([
            Paragraph(str(idx + 1), normal),
            Paragraph(sec.get("section", ""), normal),
            Paragraph(sec.get("subject", ""), normal),
            Paragraph(sec.get("summary", ""), normal),
        ])

    table = Table(
        table_data,
        # colWidths=[40, 100, 120, 240],  # tuned for readability
        colWidths=[40, 50, 70, 400],
        repeatRows=1  # header repeats on new page
    )

    table.setStyle(TableStyle([
        # Header styling
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),

        # Grid
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

        # Padding
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),

        # Alignments
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))

    story.append(table)
    story.append(Spacer(1, 20))

    # ---------------------------
    # 🔹 Meta (footer-like)
    # ---------------------------
    story.append(Paragraph(
        f"Generated by {meta.get('provider', '')} ({meta.get('model', '')}), with the help of Gyan Raj",
        small_gray
    ))

    # ---------------------------
    # Build PDF
    # ---------------------------
    doc.build(story)