from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.enum.table import WD_TABLE_ALIGNMENT
import json


def generate_docx_from_json(json_path, docx_path):
    with open(json_path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    data = raw["data"]
    meta = raw.get("meta", {})

    doc = Document()

    # ---------------------------
    # 🔹 Title
    # ---------------------------
    title = doc.add_heading("Risk Summary Report", level=1)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT

    doc.add_paragraph()

    # ---------------------------
    # 🔹 Summary
    # ---------------------------
    summary_heading = doc.add_heading("Summary", level=2)

    summary_para = doc.add_paragraph(data.get("remarks", ""))
    summary_para.style.font.size = Pt(11)

    doc.add_paragraph()

    # ---------------------------
    # 🔹 Risk Overview (2-column table)
    # ---------------------------
    overview_heading = doc.add_heading("Risk Overview", level=2)

    overview_table = doc.add_table(rows=1, cols=2)
    overview_table.style = "Table Grid"
    overview_table.alignment = WD_TABLE_ALIGNMENT.CENTER

    row = overview_table.rows[0]

    row.cells[0].text = f"Overall Risk\n{data.get('overall_risk', '')}"

    row.cells[1].text = f"Risk Score\n{data.get('risk_score', '')}"

    # Make text slightly bold for labels
    for cell in row.cells:
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.font.size = Pt(11)

    doc.add_paragraph()

    # ---------------------------
    # 🔹 Detailed Assessment Table
    # ---------------------------
    detail_heading = doc.add_heading("Detailed Assessment", level=2)

    sections = data.get("sections", [])

    table = doc.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Header row
    hdr_cells = table.rows[0].cells

    headers = ["S No.", "Section", "Subject", "Summary"]

    for idx, header in enumerate(headers):
        paragraph = hdr_cells[idx].paragraphs[0]
        run = paragraph.add_run(header)
        run.bold = True
        run.font.size = Pt(10)

    # Data rows
    for idx, sec in enumerate(sections):
        row_cells = table.add_row().cells

        row_cells[0].text = str(idx + 1)
        row_cells[1].text = sec.get("section", "")
        row_cells[2].text = sec.get("subject", "")
        row_cells[3].text = sec.get("summary", "")

        # Optional font sizing
        for cell in row_cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(10)

    doc.add_paragraph()

    # ---------------------------
    # 🔹 Footer / Meta
    # ---------------------------
    footer_para = doc.add_paragraph()

    footer_run = footer_para.add_run(
        f"Generated by {meta.get('provider', '')} "
        f"({meta.get('model', '')}), with the help of Gyan Raj"
    )

    footer_run.italic = True
    footer_run.font.size = Pt(9)

    # ---------------------------
    # Save DOCX
    # ---------------------------
    doc.save(docx_path)
